/**
 * ClawTell Bootstrap Hook + Workspace Setup
 * 
 * Provides 3 layers of agent instruction delivery:
 * 
 * Layer 1: agent:bootstrap hook — injects CLAWTELL.md into every agent's
 *          bootstrap context at runtime (never touches filesystem)
 * 
 * Layer 2: Startup file writer — writes CLAWTELL_INSTRUCTIONS.md to each
 *          routed agent's workspace (persistent reference)
 * 
 * Layer 3: Env var writer — ensures CLAWTELL_API_KEY is in agent's .env
 * 
 * Layer 4 (existing): messageToolHints in channel.ts — fires for ClawTell-context messages
 */

import * as fs from "node:fs/promises";
import * as path from "node:path";
import type { ClawdbotConfig } from "openclaw/plugin-sdk";

interface ClawTellRouteEntry {
  agent: string;
  forward?: boolean;
  apiKey?: string;
}

interface BootstrapFile {
  name: string;
  path: string;
  content: string;
  missing: boolean;
}

interface BootstrapContext {
  bootstrapFiles: BootstrapFile[];
  cfg: ClawdbotConfig;
  agentId?: string;
  workspaceDir?: string;
}

/**
 * Resolve the ClawTell name for a given agent from routing config.
 * Returns the first name that routes to this agent.
 */
function resolveAgentClawTellName(
  agentId: string,
  routing: Record<string, ClawTellRouteEntry>
): { name: string; apiKey?: string } | null {
  for (const [name, entry] of Object.entries(routing)) {
    if (name === "_default") continue;
    if (entry.agent === agentId) {
      return { name, apiKey: entry.apiKey };
    }
  }
  return null;
}

/**
 * Build the CLAWTELL.md content for a specific agent.
 *
 * Tool-based instructions: the agent calls the `clawtell_send` tool exposed
 * by the plugin. No shell, no curl, no env-var read. The `from` parameter
 * binds this agent's tell/ identity so multi-name accounts route through
 * the correct per-route API key.
 *
 * `workspace` and `hasRouteSpecificKey` are retained on the signature to
 * preserve the existing API surface; they are no longer used in the body
 * (the tool resolves keys from cfg at call time).
 */
function buildClawTellInstructions(opts: {
  agentId: string;
  tellName: string;
  accountName?: string;
  hasRouteSpecificKey: boolean;
  workspace: string;
}): string {
  const { tellName, accountName } = opts;

  return `# ClawTell Instructions

## Your Identity
- **ClawTell name:** \`${tellName}\`
- **Send as:** \`tell/${tellName}\`

## Sending Messages

When the user says **"tell/<name> <message>"** or **"tell <name> <message>"**:

1. Extract the **recipient name** (after \`tell/\` or \`tell \`)
2. Compose the message naturally (write as yourself) — unless the user says "send exactly this", then send verbatim
3. Call the \`clawtell_send\` tool:

\`\`\`
clawtell_send({
  to: "<recipient_name>",
  body: "<composed message>",
  subject: "<brief 3-5 word topic>",
  from: "${tellName}"
})
\`\`\`

4. On success the tool returns \`✓ Sent to tell/<recipient>\` — relay that to the chat
5. On failure, show the error and troubleshoot

## Key Rules
- Never use \`curl\`, \`python\`, or any shell command to send — the \`clawtell_send\` tool is the only supported send path.
- The tool runs as \`ownerOnly\` — only owner sessions can send.
- Always pass \`from: "${tellName}"\` so the recipient sees the correct sender (this is your tell/ name on this gateway).
- The tool reads per-route API keys from gateway config — never hardcode keys.

## Receiving Messages

ClawTell messages arrive formatted with a \`🦞🦞 ClawTell Delivery 🦞🦞\` banner.
They include the sender name and subject. Reply naturally — the system routes your reply back through ClawTell automatically.

## Troubleshooting

- **\`clawtell_send\` not available** — gateway needs restart, or the plugin's postinstall didn't add \`clawtell_send\` to your agent's \`tools.alsoAllow\`. Ask the owner to run \`openclaw gateway restart\` and verify \`agents.list[<your-id>].tools.alsoAllow\` contains \`"clawtell_send"\`.
- **\`× Send failed: ...\`** — the API call returned an error. Surface it to the human.

## Our Names
${accountName ? `Account owner: \`${accountName}\`` : ""}
All names on this account can message each other internally.

---
*Auto-generated by ClawTell plugin. Do not edit — regenerated on gateway restart.*
`;
}

// ============================================================================
// Layer 1: Bootstrap Hook
// ============================================================================

/**
 * Create the agent:bootstrap hook handler.
 * Injects CLAWTELL.md into every agent's bootstrap context.
 */
export function createBootstrapHook(cfg: ClawdbotConfig) {
  return async (event: any) => {
    const ctx = event.context;
    const clawtellConfig = (cfg.channels as any)?.clawtell;
    if (!clawtellConfig?.enabled) return;

    const routing = clawtellConfig.routing as Record<string, ClawTellRouteEntry> | undefined;
    if (!routing) return;

    const agentId = ctx.agentId || "main";
    const agentInfo = resolveAgentClawTellName(agentId, routing);

    // If this agent isn't in routing, check _default
    const tellName = agentInfo?.name || clawtellConfig.name;
    if (!tellName) return;

    const agentsConfig = (cfg as any).agents ?? {};
    const agentList: Array<{ id: string; workspace?: string }> = agentsConfig.list ?? [];
    const defaultWorkspace = agentsConfig.defaults?.workspace || path.join(process.env.HOME || "/home/claw", "workspace");
    const agentConfig = agentList.find(a => a.id === agentId);
    const workspace = ctx.workspaceDir || agentConfig?.workspace || defaultWorkspace;

    const instructions = buildClawTellInstructions({
      agentId,
      tellName,
      accountName: clawtellConfig.name,
      hasRouteSpecificKey: !!agentInfo?.apiKey,
      workspace,
    });

    // Inject CLAWTELL.md into bootstrap files
    const existing = ctx.bootstrapFiles.findIndex(f => f.name === "CLAWTELL.md");
    const entry: BootstrapFile = {
      name: "CLAWTELL.md",
      path: "CLAWTELL.md",
      content: instructions,
      missing: false,
    };

    if (existing >= 0) {
      ctx.bootstrapFiles[existing] = entry;
    } else {
      ctx.bootstrapFiles.push(entry);
    }
  };
}

// ============================================================================
// Layer 2: Startup File Writer
// ============================================================================

/**
 * Write CLAWTELL_INSTRUCTIONS.md to each routed agent's workspace.
 * Called once on gateway startup.
 */
export async function writeAgentInstructionFiles(cfg: ClawdbotConfig): Promise<void> {
  const clawtellConfig = (cfg.channels as any)?.clawtell;
  if (!clawtellConfig?.enabled) return;

  const routing = clawtellConfig.routing as Record<string, ClawTellRouteEntry> | undefined;
  if (!routing) return;

  const agentsConfig = (cfg as any).agents ?? {};
  const agentList: Array<{ id: string; workspace?: string }> = agentsConfig.list ?? [];
  const defaultWorkspace = agentsConfig.defaults?.workspace || path.join(process.env.HOME || "/home/claw", "workspace");

  // Collect unique agents from routing
  const agentNames = new Set<string>();
  for (const [name, entry] of Object.entries(routing)) {
    if (name !== "_default" && entry.agent) {
      agentNames.add(entry.agent);
    }
  }

  for (const agentId of agentNames) {
    const agentConfig = agentList.find(a => a.id === agentId);
    const workspace = agentConfig?.workspace || defaultWorkspace;
    const agentInfo = resolveAgentClawTellName(agentId, routing);
    const tellName = agentInfo?.name || clawtellConfig.name;
    if (!tellName) continue;

    const instructions = buildClawTellInstructions({
      agentId,
      tellName,
      accountName: clawtellConfig.name,
      hasRouteSpecificKey: !!agentInfo?.apiKey,
      workspace,
    });

    const filePath = path.join(workspace, "CLAWTELL_INSTRUCTIONS.md");
    try {
      await fs.writeFile(filePath, instructions, "utf8");
      console.log(`[ClawTell] Wrote ${filePath} for agent:${agentId} (tell/${tellName})`);
    } catch (err) {
      console.error(`[ClawTell] Failed to write ${filePath}:`, err);
    }
  }
}

// ============================================================================
// Layer 3: Env Var Writer
// ============================================================================

/**
 * Ensure CLAWTELL_API_KEY is set in each agent's .env file.
 * Uses the per-route key if available, otherwise account-level key.
 */
export async function writeAgentEnvVars(cfg: ClawdbotConfig): Promise<void> {
  const clawtellConfig = (cfg.channels as any)?.clawtell;
  if (!clawtellConfig?.enabled) return;

  const routing = clawtellConfig.routing as Record<string, ClawTellRouteEntry> | undefined;
  const accountApiKey = clawtellConfig.apiKey;
  if (!accountApiKey) return;

  const agentsConfig2 = (cfg as any).agents ?? {};
  const agentList2: Array<{ id: string; workspace?: string }> = agentsConfig2.list ?? [];
  const defaultWorkspace2 = agentsConfig2.defaults?.workspace || path.join(process.env.HOME || "/home/claw", "workspace");

  // Collect agents and their keys
  const agentKeys = new Map<string, string>();
  
  if (routing) {
    for (const [name, entry] of Object.entries(routing)) {
      if (name === "_default") continue;
      const key = entry.apiKey || accountApiKey;
      agentKeys.set(entry.agent, key);
    }
  }

  // Also ensure main agent has the key
  if (!agentKeys.has("main")) {
    agentKeys.set("main", accountApiKey);
  }

  for (const [agentId, apiKey] of agentKeys) {
    const agentConfig2 = agentList2.find(a => a.id === agentId);
    const workspace = agentConfig2?.workspace || defaultWorkspace2;
    const envPath = path.join(workspace, ".env");

    try {
      let envContent = "";
      try {
        envContent = await fs.readFile(envPath, "utf8");
      } catch {
        // .env doesn't exist yet — that's fine
      }

      // Check if CLAWTELL_API_KEY already exists and matches
      const keyRegex = /^CLAWTELL_API_KEY=(.+)$/m;
      const match = envContent.match(keyRegex);

      if (match && match[1] === apiKey) {
        // Already correct
        continue;
      }

      if (match) {
        // Update existing
        envContent = envContent.replace(keyRegex, `CLAWTELL_API_KEY=${apiKey}`);
      } else {
        // Append
        const separator = envContent.endsWith("\n") || envContent === "" ? "" : "\n";
        envContent += `${separator}\n# ClawTell API Key (auto-managed by plugin)\nCLAWTELL_API_KEY=${apiKey}\n`;
      }

      // Security: 0600 permissions — file contains API keys
      await fs.writeFile(envPath, envContent, { encoding: "utf8", mode: 0o600 });
      console.log(`[ClawTell] Set CLAWTELL_API_KEY in ${envPath} for agent:${agentId}`);
    } catch (err) {
      console.error(`[ClawTell] Failed to write env for agent:${agentId}:`, err);
    }
  }
}
